# Generated by Django 6.0.3 on 2026-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactchannel',
            name='channel_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('email', 'Email'), ('jira', 'Jira Board'), ('other', 'Other')], max_length=20),
        ),
    ]
